---
- name: Create script from template
  template:
    src: efi-clone.sh.j2
    dest: /usr/local/bin/efi-clone.sh
    mode: 0755

- name: Create Service from template
  template:
    src: efi-clone.service.j2
    dest: /etc/systemd/system/efi-clone.service

- name: Make sure service is enabled and running
  systemd:
    name: efi-clone.service
    enabled: yes
    state: started
